default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: depot_app
  password: D3p0tDBus3r
  socket: /tmp/mysql.sock

development:
 <<: *default
 database: depot_development

test:
 <<: *default
 database: depot_test

production:
 <<: *default
 database: depot_production 